INSERT INTO "CUSTOMER" (ID, NAME, EMAIL,PASSWORD) VALUES(1, 'Avinash','avi@yahoo.com','Avinash123');
INSERT INTO "CUSTOMER" (ID, NAME, EMAIL,PASSWORD) VALUES(2, 'Jagan','jagan@yahoo.com', 'Avinash123');
INSERT INTO "CUSTOMER" (ID, NAME, EMAIL, PASSWORD) VALUES(3, 'Adari','adari@yahoo.com', 'Avinash123');


INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(1,'2017', 'AUDI','A4','VIN55454');
INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(2,'2016', 'HONDA','ACCORD', 'VIN54654');
INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(3,'2017', 'MERCEDES BENZ','SUV', 'VIN47565');

INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(4,'2017', 'KIA','RIO','VIN46546');
INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(5,'2016', 'TESLA','MODEL S', 'VIN54542');
INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(6,'2017', 'TOYATA','CAMERY', 'VIN98787');
INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(7,'2017', 'BMW','S4','VIN79877');
INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(8,'2016', 'NISSAN','SENTRA', 'VIN4654');
INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(9,'2017', 'FORD','EXPLORER', 'VIN5444');

INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(10,'2017', 'MAZDA','A6','VIN87987');
INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(11,'2016', 'LEXUS','LS', 'VIN46564');
INSERT INTO "CARS" (ID,YEAR, MAKE, MODEL,VIN) VALUES(12,'2017', 'FORD','FIESTA', 'VIN54787');